#!/bin/bash

# exit when any command fails
set -e

export CURRENT_USER=$(id -u -n)
export WHYIS_USER=whyis
export WHYIS_GROUP=${WHYIS_GROUP:-whyis}

export WHYIS_HOME=/opt/materialsmine

export FUSEKI_SERVER=`which fuseki-server`
export FUSEKI_HOME=$PWD/fuseki
export WHYIS_APP_HOME=$PWD
export PYTHON_HOME=$(python -c 'import sys; print(sys.prefix)')
groupadd -f $WHYIS_GROUP
usermod -a -G $WHYIS_GROUP $WHYIS_USER

apt-get install -y apache2-dev \
			unzip \
			zip \
			default-jdk \
			build-essential \
			automake libblas3 \
			libblas-dev \
			python3-celery \
			redis-server \
			apache2 \
			libffi-dev \
			libssl-dev \
			maven \
			libdb5.3-dev \
			python3-dev

pip install -r $WHYIS_HOME/requirements.txt

mkdir -p $WHYIS_HOME/data/nanopublications
mkdir -p $WHYIS_HOME/fuseki
mkdir -p $WHYIS_HOME/data/files
mkdir -p $WHYIS_HOME/celery

mkdir -p /var/log/celery
chown -R $WHYIS_USER /var/log/celery
mkdir -p /var/run/celery
chown -R $WHYIS_USER /var/run/celery

mkdir -p /var/log/whyis
chown -R $WHYIS_USER /var/log/whyis

# These are here to re-substitute these variables back into the
# script, while rewriting the ones we need to.
export CELERY_BIN='${CELERY_BIN}'
export CELERYD_NODES='${CELERYD_NODES}'
export CELERY_APP='${CELERY_APP}'
export CELERYD_PID_FILE='${CELERYD_PID_FILE}'
export CELERYD_LOG_FILE='${CELERYD_LOG_FILE}'
export CELERYD_LOG_LEVEL='${CELERYD_LOG_LEVEL}'
export CELERYD_OPTS='${CELERYD_OPTS}'


# configure celery
mkdir -p /etc/conf.d
envsubst < $PWD/install_files/etc/conf.d/celery > /etc/conf.d/celery
envsubst < $PWD/install_files/celerybeat.service  > /etc/systemd/system/celerybeat.service
envsubst < $PWD/install_files/celery.service > /etc/systemd/system/celery.service
systemctl enable celery.service
systemctl enable celerybeat.service

envsubst < install_files/system.conf > system.conf

# enable wsgi
export WSGI_EXPRESS=$(which mod_wsgi-express)
$WSGI_EXPRESS module-config > /etc/apache2/mods-available/wsgi.load
a2enmod wsgi
a2enmod headers
envsubst < $PWD/install_files/etc/apache2/sites-available/000-default.conf \
	 > /etc/apache2/sites-available/000-default.conf

# set up fuseki
envsubst < $PWD/install_files/fuseki.service > /etc/systemd/system/fuseki.service

systemctl enable fuseki.service

# start services
service apache2 start
service redis-server start
systemctl start celery
systemctl start celerybeat
systemctl start fuseki

echo "Complete!"
