version: '3'
services:
  redis:
    image: "redis:alpine"
    command: redis-server
    volumes:
     - ./redis-data:/var/lib/redis
    ports:
      - '6379:6379'
  celery:
    depends_on:
      - redis
      - fuseki
    command: celery -A wsgi.celery worker -l INFO -c 4 --uid=nobody --gid=nogroup
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./materialsmine:/app
  celerybeat:
      - redis
      - fuseki
    command: celery -A wsgi.celery beat -l INFO --uid=nobody --gid=nogroup
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./materialsmine:/app
  fuseki:
    command: fuseki-server --mem /ds
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./materialsmine:/app
  web:
      - redis
      - fuseki
    stdin_open: true
    command: gunicorn wsgi:application --workers ${WEB_CONCURRENCY:-4} --timeout 90
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - ./materialsmine:/app
