FROM ubuntu:18.04
RUN apt-get update && apt-get install -y software-properties-common gcc && \
    add-apt-repository -y ppa:deadsnakes/ppa

RUN apt-get update && apt-get install -y python3 python3-distutils python3-pip python3-apt curl
WORKDIR '/apps'
CMD [ "/bin/bash" ]