version: '3'
services:
  redis:
    image: "redis:alpine"
    command: redis-server
    volumes:
     - ./mockDB/redis-data:/var/lib/redis
  celery:
    depends_on:
      - redis
      - fuseki
    command: /opt/venv/bin/celery -A wsgi.celery worker -l INFO -c 4 --uid=nobody --gid=nogroup
    volumes:
      - ./materialsmine:/app
      - ./mockDB/fuseki:/app/run
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile.dev
      context: .
  celerybeat:
    depends_on:
      - redis
      - fuseki
    command: /opt/venv/bin/celery -A wsgi.celery beat -l INFO --uid=nobody --gid=nogroup
    volumes:
      - ./materialsmine:/app
      - ./mockDB/fuseki:/app/run
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile.dev
      context: .
  fuseki:
    command: /opt/venv/bin/fuseki-server --mem /ds
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile.dev
      context: .
    ports:
      - '3030:3030'
    volumes:
      - ./materialsmine:/app
      - ./mockDB/fuseki:/app/run
  whyis:
    depends_on:
      - redis
      - fuseki
    stdin_open: true
    command: /opt/venv/bin/gunicorn wsgi:application --workers ${WEB_CONCURRENCY:-4} --timeout 90 -b :8000
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile.dev
      context: .
    volumes:
      - ./materialsmine:/app
      - ./mockDB/fuseki:/app/run
    ports:
      - '8000:8000'
      - '5000:5000'
