version: '3'
services:
  mongo:
    image: 'mongo:4.4'
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MM_MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MM_MONGO_PWD}
      - MONGO_DEVS=${MONGO_TEST}
      - MONGO_DEV_PWD=${MONGO_TEST_PWD}
      - MM_DB=${MM_DB}
    ports:
      - '27017:27017'
    volumes:
      - ./mockDB/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
  api:
    image: 'dukematsci/prod-restful:latest'
    depends_on:
      - mongo
    environment:
      - DB_USERNAME=${MONGO_TEST}
      - DB_PASSWORD=${MONGO_TEST_PWD}
      - MM_DB=${MM_DB}
      - MONGO_ADDRESS=${MONGO_ADDRESS}
      - MONGO_PORT=${MONGO_PORT}
      - TKNS=${TKNS}
      - MM_RUNTIME_ENV=${MM_RUNTIME_ENV}
  client:
    image: 'dukematsci/prod-app:latest'
    depends_on:
      - api
  kgapp:
    image: 'dukematsci/prod-kgapp:latest'

volumes:
  mockDB: