#!/bin/bash

export NVM_DIR=$HOME/.nvm;
source $NVM_DIR/nvm.sh;

args=$1
if [ "$args" == "install" ] ; then
 yes | npm i && cd app && nvm use && npm i && cd ../resfulservice && nvm use && npm i && cd .. && docker-compose build
 echo "Completed '$args' successfully!"
 exit
elif [ "$args" == "re-install" ] ; then
 yes | rm -rf node_modules && npm i && cd app && rm -rf node_modules && nvm use && npm i && cd ../resfulservice && rm -rf node_modules && nvm use && npm i && cd .. && docker system prune -a && docker-compose build
 echo "Completed '$args' successfully!"
 exit
fi
echo 'Did not understand args', "$args"