<template>
    <div class="data-row">
        <div class="article_metadata_strong md-title">More Info</div>
        <md-table
            class="u_width--max u_divider-fullspan utility-transparentbg viz-u-postion__rel viz-u-zIndex__min"
            v-model="fetchedNames"
            md-sort="key"
            md-sort-order="asc"
        >
            <md-table-empty-state md-label="No dataset info available">
            </md-table-empty-state>
            <template #md-table-row="{ item }">
                <md-table-row :key="item.name">
                    <md-table-cell md-label="Name" md-sort-by="name">
                        <div>
                            <h3>Data info:</h3>
                            <md-chip
                                :style="{
                                    'background-color': item.color,
                                    color: 'white'
                                }"
                                >{{ item.name }}</md-chip
                            >
                            <h3>Author(s):</h3>
                            <p>Northwestern University</p>
                            <h3>Description:</h3>
                            <p>
                                This database contains 248396 orthotropic
                                microstructures represented by 50x50 pixelated
                                matrices as well as the associated independent
                                components of the stiffness tensor calculator by
                                energy-based homogenization, i.e.,C11 ,C12 , C22
                                and C66. The microstructures are composed of
                                void (air) and solid (Young’s
                                modulus=1(normalized), Poisson’s ratio=0.49). We
                                first performed SIMP-based TO to find a
                                corresponding pixelated microstructure design
                                for each uniformly sampled target stiffness
                                matrix. With 1400 microstructures generated by
                                TO as initial seeds, an iterative stochastic
                                shape perturbation algorithm is employed to
                                perturb microstructure geometries that
                                correspond to extreme and sparse properties. The
                                CMAME version of database (240k) is extended
                                from the SMO version (88k).
                            </p>
                        </div>
                    </md-table-cell>
                </md-table-row>
            </template>
        </md-table>
    </div>
</template>

<script>
import { mapState } from 'vuex'

export default {
  name: 'DataInfo',
  computed: {
    ...mapState('metamineNU', {
      fetchedNames: (state) => state.fetchedNames
    })
  }
}
</script>
