<template>
    <div class="data-selector-wrapper">
        <div class="data-row">
            <div style="font-size: 20px; font-weight: bold; padding: 0px">
                Data
            </div>
            <a-table
                :columns="columns"
                :data-source="this.fetchedNames"
                :row-selection="rowSelection"
                :expanded-row-keys.sync="expandedRowKeys"
                :scroll="{ y: 200 }"
            >
                <span
                    slot="expandedRowRender"
                    slot-scope="record"
                    style="margin: 0"
                >
                    <h3>Data info:</h3>
                    <p>{{ record.name }}</p>
                    <h3>Author(s):</h3>
                    <p>Northwestern University</p>
                    <h3>Description:</h3>
                    <p>
                        This database contains 248396 orthotropic
                        microstructures represented by 50x50 pixelated matrices
                        as well as the associated independent components of the
                        stiffness tensor calculator by energy-based
                        homogenization, i.e.,C11 ,C12 , C22 and C66. The
                        microstructures are composed of void (air) and solid
                        (Young’s modulus=1(normalized), Poisson’s ratio=0.49).
                        We first performed SIMP-based TO to find a corresponding
                        pixelated microstructure design for each uniformly
                        sampled target stiffness matrix. With 1400
                        microstructures generated by TO as initial seeds, an
                        iterative stochastic shape perturbation algorithm is
                        employed to perturb microstructure geometries that
                        correspond to extreme and sparse properties. The CMAME
                        version of database (240k) is extended from the SMO
                        version (88k).
                    </p>
                </span>
            </a-table>
        </div>
        <div v-if="page === 'scatter'">
            <div
                style="display: 'flex'; flex-direction: column; margin: 5px 0px"
            >
                <p>X-axis</p>
                <a-select
                    :default-value="query1"
                    @change="handleQuery1Change"
                    style="width: 100%"
                >
                    <a-select-option value="C11">C11</a-select-option>
                    <a-select-option value="C12">C12</a-select-option>
                    <a-select-option value="C22">C22</a-select-option>
                    <a-select-option value="C16">C16</a-select-option>
                    <a-select-option value="C26">C26</a-select-option>
                    <a-select-option value="C66">C66</a-select-option>
                </a-select>
            </div>
            <div
                style="display: 'flex'; flex-direction: column; margin: 5px 0px"
            >
                <p>Y-axis</p>
                <a-select
                    :default-value="query2"
                    @change="handleQuery2Change"
                    style="width: 100%"
                >
                    <a-select-option value="C11">C11</a-select-option>
                    <a-select-option value="C12">C12</a-select-option>
                    <a-select-option value="C22">C22</a-select-option>
                    <a-select-option value="C16">C16</a-select-option>
                    <a-select-option value="C26">C26</a-select-option>
                    <a-select-option value="C66">C66</a-select-option>
                </a-select>
            </div>
        </div>
        <div v-if="page === 'hist'">
                      <div
                style="display: 'flex'; flex-direction: column; margin: 5px 0px"
            >
                <p>X-axis</p>
                <a-select
                    :default-value="query1"
                    @change="handleQuery1Change"
                    style="width: 100%"
                >
                    <a-select-option value="C11">C11</a-select-option>
                    <a-select-option value="C12">C12</a-select-option>
                    <a-select-option value="C22">C22</a-select-option>
                    <a-select-option value="C16">C16</a-select-option>
                    <a-select-option value="C26">C26</a-select-option>
                    <a-select-option value="C66">C66</a-select-option>
                </a-select>
            </div>
        </div>
    </div>
</template>

<script>
import { mapState } from 'vuex'
import { Table, Select } from 'ant-design-vue'

const columns = [
  {
    title: 'Name',
    dataIndex: 'name',
    key: 'name',
    width: '80%'
  }
]

export default {
  name: 'DataSelector',
  components: {
    'a-table': Table,
    'a-select': Select
  },
  mounted () {
    if (!this.query1) {
      this.$store.dispatch(
        'metamineNU/setQuery1',
        this.$route.query.pairwise_query1
      )
    }
    if (!this.query2) {
      this.$store.dispatch(
        'metamineNU/setQuery2',
        this.$route.query.pairwise_query2
      )
    }
  },
  computed: {
    ...mapState('metamineNU', {
      activeData: (state) => state.activeData,
      fetchedNames: (state) => state.fetchedNames,
      dataLibrary: (state) => state.dataLibrary,
      page: (state) => state.page,
      query1: (state) => state.query1,
      query2: (state) => state.query2
    }),
    rowSelection () {
      const self = this
      return {
        selectedRowKeys: self.selectedRowKeys,
        onChange: (selectedRowKeys, selectedRows) => {
          self.selectedRowKeys = selectedRowKeys
        },
        onSelect: (record, selected, selectedRows) => {
          if (selected) {
            let sourceItems = self.activeData
            let destItems = self.dataLibrary
            const checked = destItems.filter(
              (item) => item.name === record.name
            )
            destItems = destItems.filter(
              (item) => item.name !== record.name
            )
            sourceItems = [...sourceItems, ...checked]
            self.$store.dispatch(
              'metamineNU/setActiveData',
              sourceItems
            )
            self.$store.dispatch(
              'metamineNU/setDataLibrary',
              destItems
            )
          } else {
            let sourceItems = self.dataLibrary
            let destItems = self.activeData
            const unchecked = destItems.filter(
              (item) => item.name === record.name
            )
            destItems = destItems.filter(
              (item) => item.name !== record.name
            )
            sourceItems = [...sourceItems, ...unchecked]
            self.$store.dispatch(
              'metamineNU/setActiveData',
              destItems
            )
            self.$store.dispatch(
              'metamineNU/setDataLibrary',
              sourceItems
            )
          }
        },
        onSelectAll: (selected, selectedRows, changeRows) => {
          if (selected) {
            selectedRows.map((record, index) => {
              let sourceItems = self.activeData
              let destItems = self.dataLibrary
              const checked = destItems.filter(
                (item) => item.name === record.name
              )
              destItems = destItems.filter(
                (item) => item.name !== record.name
              )
              sourceItems = [...sourceItems, ...checked]
              self.$store.dispatch(
                'metamineNU/setActiveData',
                destItems
              )
              self.$store.dispatch(
                'metamineNU/setDataLibrary',
                sourceItems
              )
            })
          } else {
            selectedRows.map((record, index) => {
              let sourceItems = self.dataLibrary
              let destItems = self.activeData
              const unchecked = destItems.filter(
                (item) => item.name === record.name
              )
              destItems = destItems.filter(
                (item) => item.name !== record.name
              )
              sourceItems = [...sourceItems, ...unchecked]
              self.$store.commit(
                'metamineNU/setActiveData',
                destItems
              )
              self.$store.commit(
                'metamineNU/setDataLibrary',
                sourceItems
              )
            })
          }
        }
      }
    }
  },
  data () {
    return {
      columns,
      expandedRowKeys: [],
      selectedRowKeys: []
    }
  },
  watch: {
    fetchedNames: {
      handler: function (val, oldVal) {
        this.data = val
        this.selectedRowKeys = val.map((item) => item.key)
      },
      deep: true
    },
    activeData: {
      handler: function (val, oldVal) {
        this.selectedRowKeys = this.fetchedNames.map(item => { return val.map(d => d.name).includes(item.name) ? item.key : null }).filter(item => item !== null)
      },
      deep: true
    },
    dataLibrary: {
      handler: function (val, oldVal) {},
      deep: true
    }
  },
  methods: {
    handleQuery1Change (value) {
      this.$store.dispatch('metamineNU/setQuery1', value)
    },
    handleQuery2Change (value) {
      this.$store.dispatch('metamineNU/setQuery2', value)
    }
  }
}
</script>

<style lang="scss" scoped>
.md-table + .md-table {
    margin-top: 16px;
}
</style>
