server {
  listen 8080;
  server_name qa.materialsmine.org;
  root   /usr/share/nginx/html;
  autoindex off;

  # Required Headers
  add_header X-Frame-Options "SAMEORIGIN" always;
  add_header X-Permitted-Cross-Domain-Policies "master-only" always;
  add_header X-Content-Type-Options "nosniff" always;
  add_header Referrer-Policy "same-origin";
  add_header X-XSS-Protection "1; mode=block" always;
  add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;

  add_header X-Permitted-Cross-Domain-Policies "none" always;
  add_header X-Download-Options "noopen" always;
  
  # will remove based on Impact: Turning DNS prefetching off can slightly reduce performance if the app loads resources from multiple domains. But it can also reduce tracking or unexpected DNS requests.
  add_header X-DNS-Prefetch-Control "off";

  location ~ /\. {
    deny all;
    access_log off;
    log_not_found off;
  }

  # ----------------------------------------------------------
  # 1) Long cache for JS/CSS (3 weeks = 1814400 seconds)
  # ----------------------------------------------------------
  location ~* \.(?:css|js)$ {
    expires 4w;
    add_header Cache-Control "public, max-age=2419200" always;
    try_files $uri =404; 
  }

  # ----------------------------------------------------------
  # 2) Short or no cache for HTML
  # ----------------------------------------------------------
  location ~* \.html?$ {
    add_header Cache-Control "no-cache, must-revalidate" always;
    try_files $uri =404;
  }

  # ----------------------------------------------------------
  # 3) Catch-all for other assets 
  #     (images, fonts, etc.) with a moderate or similar cache
  # ----------------------------------------------------------
  location ~* \.(?:png|jpg|webp|jpeg|gif|svg|ico|woff|woff2|ttf|eot)$ {
    add_header Cache-Control "public, max-age=15552000, immutable";
    expires 6M;
    access_log off;
    try_files $uri =404;
  }

  # Serve static files
  location / {
    try_files $uri $uri/ /index.html;
  }

  location = /sitemap.xml {
    try_files /sitemap.xml =404;
    add_header Content-Type application/xml;
  }
  
  location = /robots.txt {
    try_files /robots.txt =404;
    add_header Content-Type text/plain;
  }
}