#!/bin/bash
mongo --port $NM_MONGO_PORT -u $NM_MONGO_USER -p $NM_MONGO_PWD --authenticationDatabase admin <<EOF
use admin
db.updateUser(
  "{$NM_MONGO_USER}",
  { 
  pwd: "{$NM_MONGO_PWD}",
  roles: [ { role: "userAdminAnyDatabase", db: "admin"},
           { role: "readWrite", db: "ChemProps"},
           { role: "readWrite", db: "unknowns"},
           "backup","restore"
         ]
});
EOF

