#!/bin/bash
mongo --port $MONGO_PORT -u $CHEMPROPS_USER -p $CHEMPROPS_PWD --authenticationDatabase admin <<EOF
use admin
db.updateUser(
  "{$CHEMPROPS_USER}",
  { 
  pwd: "{$CHEMPROPS_PWD}",
  roles: [ { role: "userAdminAnyDatabase", db: "admin"},
           { role: "readWrite", db: "ChemProps"},
           { role: "readWrite", db: "unknowns"},
           "backup","restore"
         ]
});
EOF

